FROM python:3.7
ENV PYTHUONBUFFERED 1
ADD ./ app
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
CMD python tic_toc_toe.py
FROM python:3.7
ENV PYTHUONBUFFERED 1
ADD . /app
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
CMD ["python3","-m","streamlit","run","--host-0.0.0.0"]
